# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

theme: minima

title   : neurosopher
description: Adrian Valente's blog # this means to ignore newlines until "Language & timezone"
  
header_pages:
  - index.md
  - cv.md
  - blog.md
  - research.md
show_excerpts: true


## => Language and Timezone
##############################
lang: # the language of your site, default as "en"
timezone: # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: adrian-valente/adrian-valente.github.io
repository_tree: master


## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  archive : # "/archive.html" (default)
  rss     : # "/feed.xml" (default)


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-NC-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: # "h1,h2,h3" (default)


## => Markdown Enhancements
##############################
markdown: kramdown
## Mathjax
# mathjax: true # false (default), true
# mathjax_autoNumber: true # false (default), true

# ## Mermaid
# mermaid: # false (default), true

# ## Chart
# chart: # false (default), true


## => Paginate
##############################
paginate: 8
paginate_path: /page:num # don't change this unless for special need


## => Sources
##############################
sources: # bootcdn (default), unpkg

  social_links:
    github:  adrian-valente
